baseURL: https://zezhou-tang.netlify.app
languageCode: en-us
title: Portfolio website for Zezhou Tang
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    image: spices.jpg
    buttonText: Get Started
    # slug: risk_return
    #subtitle: |-
      # A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      # AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Zezhou Tang.
  blog: {}
  contact:
    address:
      - city: London, NW8 6EB
        country: UK
        street: 16A, Finchley Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ztang.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (86) 13588155725
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Zezhou Tang
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #  label: Twitter
      #  url: https://www.twitter.com
      # - icon: fa-facebook
      #  label: Facebook
      #  url: https://www.facebook.com
      # - icon: fa-instagram
      #  label: Instagram
      #  url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/Zezhou-Tang
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/elijah-zezhou-tang/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Risk Return
        url: blogs/risk_return
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: About Me
        url: blogs/about_me
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Homework 1
        url: blogs/homework1
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
